### ISSUE TITLE
Custom claims NoSuchMethodError

### ISSUE THREAD

**Issue by Mistic92** [firebase/firebase-admin-java#112]
### [REQUIRED] Step 2: Describe your environment

  * Library version: 5.6.0
  * Firebase Product: auth

### [REQUIRED] Step 3: Describe the problem
I just upgraded to 5.6.0 version to try custom claims and now I can't get user because I get NoSuchMethodError

```
Exception in thread "firebase-default-0" java.lang.NoSuchMethodError: org.json.JSONObject.toMap()Ljava/util/Map;
	at com.google.firebase.auth.UserRecord.<init>(UserRecord.java:85)
	at com.google.firebase.auth.FirebaseUserManager.getUserById(FirebaseUserManager.java:112)
	at com.google.firebase.auth.FirebaseAuth$3.call(FirebaseAuth.java:266)
	at com.google.firebase.auth.FirebaseAuth$3.call(FirebaseAuth.java:263)
	at com.google.firebase.tasks.Tasks$1.run(Tasks.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

#### Steps to reproduce:
So what I did. 
I wanted to keep previous claims so I created copy of map and add new key-val. 
```
    @Override
    public void addUserCustomClaims(final String userId, String key, String val) {
        final UserRecord user = getUser(userId);
        final Map<String, Object> customClaims = new HashMap<>(user.getCustomClaims());
        customClaims.put(key, val);
        final Void aVoid = Single.fromFuture(
            firebaseAuth.setCustomUserClaimsAsync(userId, customClaims))
            .blockingGet();
    }
```

It was inserted as I see but now I can't get user because it's throwing exception. 
With breakpoint set to https://github.com/firebase/firebase-admin-java/blob/82510ac1fc518dd80061ccfbe9a5131ae938ac29/src/main/java/com/google/firebase/auth/UserRecord.java#L85
I see values 
```
customClaims={"u_type":"USER"}
this.customClaims=null
```

**Comment by hiranya911** [comment]
Your app is using an incompatible version of the `org.json:json` dependency. You will have to inspect your dependency tree and ensure that there are no conflicting or incompatible artifacts. Here's what Firebase uses: https://github.com/firebase/firebase-admin-java/blob/master/pom.xml#L423

**Comment by jfzr** [comment]
This problem is still happening. Problem with Spring Test boot which have the vaadin dependency causing the problem

**Comment by Mistic92** [comment]
@jfzr try to add this
```
configurations {
    compile.exclude module: "android-json"
    compile.exclude module: "com.vaadin.external.google"
}
```
