### ISSUE TITLE
Error obtaining database reference, version >= 5.6.0 only.

### ISSUE THREAD

**Issue by engeeaitch** [firebase/firebase-admin-java#170]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google App Engine
  * Firebase SDK version: 5.11.0
  * Library version: com.google.firebase:firebase-admin:5.11.0
  * Firebase Product: database

### [REQUIRED] Step 3: Describe the problem

My app starts up and then listens for changes to my Firebase Database.  I am running my app in Google App Engine, and have recently been getting lots of the following errors:
“The process handling this request unexpectedly died. This is likely to cause a new process to be used for the next request to your application. (Error code 203)”  These errors occur every 30 minutes or so, and the App restarts, even if there are no changes to the database.

In an attempt to debug this, I have been running my app locally, but I always get the following error on initialising and then obtaining the reference to my Firebase Database:
[FirebaseDatabaseWorker] ERROR com.google.firebase.database.core.RunLoop - Uncaught exception in Firebase Database runloop (5.11.0). Please report to firebase-database-client@google.com
java.lang.NoClassDefFoundError: java.nio.channels.spi.SelectorProvider is a restricted class. Please see the Google  App Engine developer's guide for more details.
	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:50)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at com.google.firebase.database.connection.NettyWebSocketClient.<init>(NettyWebSocketClient.java:72)
	at com.google.firebase.database.connection.WebsocketConnection$DefaultWSClientFactory.newClient(WebsocketConnection.java:435)
	at com.google.firebase.database.connection.WebsocketConnection.<init>(WebsocketConnection.java:80)
	at com.google.firebase.database.connection.WebsocketConnection.<init>(WebsocketConnection.java:68)
	at com.google.firebase.database.connection.Connection$DefaultWebsocketConnectionFactory.newConnection(Connection.java:297)
	at com.google.firebase.database.connection.Connection.<init>(Connection.java:72)
	at com.google.firebase.database.connection.Connection.<init>(Connection.java:57)
	at com.google.firebase.database.connection.PersistentConnectionImpl$DefaultConnectionFactory.newConnection(PersistentConnectionImpl.java:1303)
	at com.google.firebase.database.connection.PersistentConnectionImpl.openNetworkConnection(PersistentConnectionImpl.java:547)
	at com.google.firebase.database.connection.PersistentConnectionImpl.access$800(PersistentConnectionImpl.java:37)
	at com.google.firebase.database.connection.PersistentConnectionImpl$1$1.onSuccess(PersistentConnectionImpl.java:500)
	at com.google.firebase.database.core.Context$1$1.onSuccess(Context.java:67)
	at com.google.firebase.database.core.JvmAuthTokenProvider.getToken(JvmAuthTokenProvider.java:66)
	at com.google.firebase.database.core.Context$1.getToken(Context.java:62)
	at com.google.firebase.database.connection.PersistentConnectionImpl$1.run(PersistentConnectionImpl.java:490)
	at com.google.firebase.database.connection.util.RetryHelper$1.run(RetryHelper.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.google.appengine.tools.development.BackgroundThreadFactory$1$1.run(BackgroundThreadFactory.java:60)

I don’t get the same errors when running in Google App Engine.   I have noticed that this only occurs when I use firebase-admin 5.6.0 or greater.  I do not get this error with version 5.5.0

Any ideas what I should do to resolve this please?

#### Steps to reproduce:

Start the app in a local environment (Android Studio)

#### Relevant Code:

```
DatabaseReference ref = FirebaseDatabase.getInstance().getReference();
//N.B. It's the call to getReference() that creates the error, not getInstance()
```

**Comment by hiranya911** [comment]
Update your gcloud components (specifically the dev app server), and use the GAE Java 8 runtime which does not restrict access to the `SelectorProvider` class. That fact that you're not seeing this error in the cloud means you're already using java8 in production.

From: https://cloud.google.com/appengine/docs/standard/java/jrewhitelist

> This whitelist does not apply to the Java 8 runtime, which supports all public JDK APIs.
