### ISSUE TITLE
NullPointerException when FirebaseInstanceId.unsubscribeFromTopic()

### ISSUE THREAD

**Issue by HDHunter** [firebase/firebase-admin-java#231]
### [READ] Step 1: the detail  .
I use fabric catch a exception .
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.zza(java.lang.String)' on a null object reference
       at com.google.firebase.messaging.FirebaseMessaging.unsubscribeFromTopic(Unknown Source:21)
       at com.chope.gui.utils.ChopeFirebaseMessageUtils.subscribeLanguageTopic(ChopeFirebaseMessageUtils.java:105)
       at com.chope.gui.ChopeApplication.initLocalLanguage(ChopeApplication.java:193)
       at com.chope.gui.ChopeApplication.onCreate(ChopeApplication.java:69)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6428)
       at android.app.ActivityThread.access$1800(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

in ChopeFirbaseMessageUtils:
` FirebaseMessaging firebaseMessaging = FirebaseMessaging.getInstance();
        ChopeFirebaseMessageUtils firebaseMessageUtils = new ChopeFirebaseMessageUtils(cxt, firebaseMessaging);`

so , now problem is why FirebaseMessaging.getInstance() is a null object .
I have already init firebaseApp  before the method invoke in Application onCreate .
 

### [REQUIRED] Step 2:environment and version.
    'com.google.firebase:firebase-core:16.0.5'
    'com.google.firebase:firebase-messaging:17.3.4'
fabric no show SystemVersion and place .

#### Steps to reproduce:
exectly we don't know how to reproduct .

**Comment by hiranya911** [comment]
This is the server-side Java Admin SDK. You're looking for https://github.com/firebase/firebase-android-sdk
