### ISSUE TITLE
Error Obtaining Database Reference

### ISSUE THREAD

**Issue by shindemanoj** [firebase/firebase-admin-java#257]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google App Engine
  * Firebase SDK version: com.google.firebase:firebase-admin:6.7.0
  * Library version: _____
  * Firebase Product: database

### [REQUIRED] Step 3: Describe the problem
Hello,
I am getting following exception, when I am trying to run app locally.
Can you please help me to resolve the issue?

com.google.firebase.database.core.JvmPlatform$1 handleException
SEVERE: Uncaught exception in Firebase Database runloop (6.7.0). Please report to firebase-database-client@google.com
java.lang.NoClassDefFoundError: java.nio.channels.spi.SelectorProvider is a restricted class. Please see the Google  App Engine developer's guide for more details.
	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at com.google.firebase.database.connection.NettyWebSocketClient.<init>(NettyWebSocketClient.java:71)
	at com.google.firebase.database.connection.WebsocketConnection$DefaultWSClientFactory.newClient(WebsocketConnection.java:417)
	at com.google.firebase.database.connection.WebsocketConnection.<init>(WebsocketConnection.java:81)
	at com.google.firebase.database.connection.WebsocketConnection.<init>(WebsocketConnection.java:70)
	at com.google.firebase.database.connection.Connection$DefaultWebsocketConnectionFactory.newConnection(Connection.java:267)
	at com.google.firebase.database.connection.Connection.<init>(Connection.java:75)
	at com.google.firebase.database.connection.Connection.<init>(Connection.java:61)
	at com.google.firebase.database.connection.PersistentConnectionImpl$DefaultConnectionFactory.newConnection(PersistentConnectionImpl.java:1247)
	at com.google.firebase.database.connection.PersistentConnectionImpl.openNetworkConnection(PersistentConnectionImpl.java:531)
	at com.google.firebase.database.connection.PersistentConnectionImpl.access$900(PersistentConnectionImpl.java:38)
	at com.google.firebase.database.connection.PersistentConnectionImpl$1$1.onSuccess(PersistentConnectionImpl.java:484)
	at com.google.firebase.database.core.Context$1$1.onSuccess(Context.java:62)
	at com.google.firebase.database.core.JvmAuthTokenProvider.getToken(JvmAuthTokenProvider.java:66)
	at com.google.firebase.database.core.Context$1.getToken(Context.java:57)
	at com.google.firebase.database.connection.PersistentConnectionImpl$1.run(PersistentConnectionImpl.java:474)
	at com.google.firebase.database.connection.util.RetryHelper$1.run(RetryHelper.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
#### Steps to reproduce:

Start the app in local environment.

#### Relevant Code:

DatabaseReference ref = FirebaseDatabase.getInstance().getReference();
// Getting Exception at this line

My appengine-web.xml

```
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
    <application>test</application>
    <version>1</version>
    <threadsafe>true</threadsafe>
    <manual-scaling>
        <instances>2</instances>
    </manual-scaling>
    <system-properties>
        <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
    </system-properties>
    <runtime>java8</runtime>
    <url-stream-handler>native</url-stream-handler>
    <warmup-requests-enabled>true</warmup-requests-enabled>
</appengine-web-app>
```

**Comment by hiranya911** [comment]
Can you try this in production App Engine? I think this is most likely a bug in the App Engine dev app server you're using. We have a bunch of users who are using this library in App Engine (myself included).

**Comment by shindemanoj** [comment]
Thanks. I am reading data with REST now.
