### ISSUE TITLE
Possible bug: Is ApsConfig#aps really mandatory?

### ISSUE THREAD

**Issue by christopher-cudennec** [firebase/firebase-admin-java#275]
* Firebase SDK version: 6.8.0
  * Firebase Product: messaging

We want to send simple push notifications with a title and a collapse-id for grouping. 

We use the message's `Notification#title` for title and want to set the collapse-id as `apns-collapse-id` header of `ApnsConfig`. When creating the `ApnsConfig` we get the error "aps must be specified" because it is checked as mandatory. However, the Aps must not simply be empty. Our workaround is creating an Aps and copying the title from the notification to the `ApsAlert`.

My question: Isn't this a bug because Firebase should be able to handle this situation itself?

Thanks!

**Comment by hiranya911** [comment]
APNs documentation states:

> The JSON dictionary object must contain an aps key, the value of which is a dictionary containing data used by the system to deliver the notification. 

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

The SDK does support specifying an empty Aps. Doesn't that work for you:

```
Message message = Message.builder()
        .setApnsConfig(ApnsConfig.builder()
            .putHeader("k1", "v1")
            .setAps(Aps.builder().build())
            .build())
        .setTopic("test-topic")
        .build();
```

**Comment by christopher-cudennec** [comment]
I'm afraid "aps" must not be empty. See the following exception:
```
com.google.firebase.messaging.FirebaseMessagingException: Value of [aps] must be a non-empty dictionary.
        at com.google.firebase.messaging.FirebaseMessagingClient.newException(FirebaseMessagingClient.java:219)
        at com.google.firebase.messaging.FirebaseMessagingClient.newException(FirebaseMessagingClient.java:199)
        at com.google.firebase.messaging.FirebaseMessagingClient.access$300(FirebaseMessagingClient.java:52)
        at com.google.firebase.messaging.FirebaseMessagingClient$MessagingBatchCallback.onFailure(FirebaseMessagingClient.java:236)
        at com.google.firebase.messaging.FirebaseMessagingClient$MessagingBatchCallback.onFailure(FirebaseMessagingClient.java:222)
        at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:223)
        at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
        at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
        at com.google.firebase.messaging.FirebaseMessagingClient.sendBatchRequest(FirebaseMessagingClient.java:141)
        at com.google.firebase.messaging.FirebaseMessagingClient.sendAll(FirebaseMessagingClient.java:110)
        at com.google.firebase.messaging.FirebaseMessaging$2.execute(FirebaseMessaging.java:296)
        at com.google.firebase.messaging.FirebaseMessaging$2.execute(FirebaseMessaging.java:293)
        at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
        at com.google.firebase.messaging.FirebaseMessaging.sendAll(FirebaseMessaging.java:187)
        at com.google.firebase.messaging.FirebaseMessaging.sendAll(FirebaseMessaging.java:164)
```

Cheers,

Christopher

**Comment by hiranya911** [comment]
That's an error sent by the FCM backend. Which means it's validated and required at that level too.

@chong-shao what do you think?

**Comment by christopher-cudennec** [comment]
Any updates? @hiranya911 / @chong-shao

**Comment by chong-shao** [comment]
ApnsConfig#aps is mandatory according to the doc: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

If ApnsConfig#aps is present, it must be non-empty because: 1. the title of notification is required. 2. for hidden messages, the flag content-available=1 in aps is required.

**Comment by christopher-cudennec** [comment]
You're absolutely right!

> We use the message's Notification#title for title 

What I'm saying is: In my opinion the SDK should be aware of these restrictions and set the altert title accordingly. From the client/user's perspective "it should just work" no matter what the implementation details are. Would you agree?

**Comment by christopher-cudennec** [comment]
@hiranya911 : I would suggest that the client library addresses that issue. It should only send requests that match the specification. What do you think?

**Comment by chong-shao** [comment]
I thought about this more carefully: the story is AdminSDK talks to FCM HTTP v1 API. The API has the platform override feature: If the APNs payload is present in your request, the backend overrides the general notification title and body with the values in APNs payload. 

On the other hand, in HTTP v1 API you can leave ApnsConfig empty in the request and just use the general notification setting in sending to an iOS device. 

Therefore I think if a general notification is set in the request, the backend should not enforce a non-empty aps field. Currently it enforces it when ApnsConfig is set in the request. I will later confirm this issue with the team and potentially rollout a fix. The fix should be on our backend and AdminSDK should be unchanged.

**Comment by christopher-cudennec** [comment]
That sounds great! Could you post a reference to the backend issue?
Thanks for your effort!

**Comment by chong-shao** [comment]
Hi @christopher-cudennec , sorry for the late reply. We don't have a reference now. I will update here after the issue has been resolved.

**Comment by chong-shao** [comment]
Hi @christopher-cudennec , sorry for the wait, now the empty ApnsConfig#aps should be accepted.

**Comment by christopher-cudennec** [comment]
Great, thanks! :)
