### ISSUE TITLE
Firebase Admin SDK issue with Window 32 bit

### ISSUE THREAD

**Issue by VishalThareja** [firebase/firebase-admin-java#313]
With Firebase Admin SDK. facing in window 10 32-bit O.S.

<dependency>
<groupId>com.google.firebase</groupId>
<artifactId>firebase-admin</artifactId>
<version>6.8.1</version>
</dependency>

An error which we received:

java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]
        at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:93) ~[grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:430) ~[grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97) ~[grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:242) [grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171) [grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120) [grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:558) [grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:551) [grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:489) [grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:337) [grpc-netty-shaded-1.13.1.jar!/:1.13.1]
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:405) [grpc-core-1.13.1.jar!/:1.13.1]
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:206) [gax-grpc-1.30.0.jar!/:1.30.0]
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:157) [gax-grpc-1.30.0.jar!/:1.30.0]
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:149) [gax-grpc-1.30.0.jar!/:1.30.0]
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:151) [gax-1.30.0.jar!/:1.30.0]
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:116) [gax-1.30.0.jar!/:1.30.0]
        at com.google.cloud.firestore.spi.v1beta1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:121) [google-cloud-firestore-0.61.0-beta.jar!/:0.61.0-beta]
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:80) [google-cloud-firestore-0.61.0-beta.jar!/:0.61.0-beta]
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:72) [google-cloud-firestore-0.61.0-beta.jar!/:0.61.0-beta]
        at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:512) [google-cloud-core-1.43.0.jar!/:1.43.0]
        at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:315) [google-cloud-firestore-0.61.0-beta.jar!/:0.61.0-beta]
        at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:76) [google-cloud-firestore-0.61.0-beta.jar!/:0.61.0-beta]
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:63) [google-cloud-firestore-0.61.0-beta.jar!/:0.61.0-beta]
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:56) [google-cloud-firestore-0.61.0-beta.jar!/:0.61.0-beta]
        at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:499) [google-cloud-core-1.43.0.jar!/:1.43.0]
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51) [firebase-admin-6.8.1.jar!/:na]
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29) [firebase-admin-6.8.1.jar!/:na]
        at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95) [firebase-admin-6.8.1.jar!/:na]
        at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85) [firebase-admin-6.8.1.jar!/:na]
        at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78) [firebase-admin-6.8.1.jar!/:na]
        at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64) [firebase-admin-6.8.1.jar!/:na]
        at com.cloud.sync.firebaseAuth.downloading.service.imp.FireBaseInitialize.loadFireBaseDB(FireBaseInitialize.java:54) [classes!/:0.0.2-SNAPSHOT]
        at com.cloud.sync.firebaseAuth.downloading.service.imp.FireBaseInitialize.<init>(FireBaseInitialize.java:49) [classes!/:0.0.2-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [na:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [na:1.8.0_221]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170) [spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) [spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]

**Comment by hiranya911** [comment]
Try upgrading `google-cloud-firestore` to the latest. Currently your app is picking up `google-cloud-firestore-0.61.0-beta.jar`. You can declare a direct dependency on 1.22.0 and see if that helps.

**Comment by VishalThareja** [comment]
Basically I am using Firebase Admin SDK and its version is: com.google.firebase firebase-admin 6.8.1
and also I have upgraded it to latest version 6.10.0, still don't solve the problem.

**Comment by hiranya911** [comment]
That's ok. Try adding a direct dependency on latest `google-cloud-firestore` library as mentioned in my previous comment.

**Comment by VishalThareja** [comment]
Yes, we have tried with adding dependency of 

<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-firestore</artifactId>
    <version>1.22.0</version>
</dependency>

but these dependencies not having subsequent classes which we were there in Firebase Admin SDK. So, we can access those classes.

**Comment by hiranya911** [comment]
You need to declare both `firebase-admin` and `google-cloud-firestore` as dependencies.

Admin SDK doesn't have any Firestore-related code. All Firestore support is provided by the `google-cloud-firestore` library. Admin SDK's `FirestoreClient` class is just a thin wrapper around the classes available in `google-cloud-firestore`. 

The latest version of the Admin SDK pulls in v1.9.0 of Firestore. But there are more recent versions where the above error is already fixed. To test this you need to have both libraries listed as dependencies.

**Comment by VishalThareja** [comment]
Can I connect with you?

**Comment by hiranya911** [comment]
If upgrading to the latest Firestore library doesn't resolve the issue, then you should probably file a support issue: https://firebase.google.com/support

Or contact the Firestore SDK team directly via https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-firestore

As I said `firebase-admin` is a very thin wrapper around the Firestore SDK, and there's not much we can do in this repo about it beyond upgrading the version of the dependency.

**Comment by hiranya911** [comment]
Closing this, as we don't have mitigation strategy from this repo.
