### ISSUE TITLE
Firebase method missing in Java

### ISSUE THREAD

**Issue by alishah730** [firebase/firebase-admin-java#330]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac/Windows 
  * Firebase SDK version: firebase-admin
  * Library version: 6.11.0
  * Firebase Product: firebase-admin

### [REQUIRED] Step 3: Describe the problem
code compiles successfully but when executing getting method not found.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.google.firebase.ImplFirebaseTrampolines.getService(Lcom/google/firebase/FirebaseApp;Ljava/lang/String;Ljava/lang/Class;)Lcom/google/firebase/internal/FirebaseService;] with root cause
java.lang.NoSuchMethodError: com.google.firebase.ImplFirebaseTrampolines.getService(Lcom/google/firebase/FirebaseApp;Ljava/lang/String;Ljava/lang/Class;)Lcom/google/firebase/internal/FirebaseService;
	at com.google.firebase.messaging.FirebaseMessaging.getInstance(FirebaseMessaging.java:73)
	at com.google.firebase.messaging.FirebaseMessaging.getInstance(FirebaseMessaging.java:64)
#### Relevant Code:

```
// TODO(you): code here to reproduce the problem

List<String> registrationTokens = Arrays.asList(
    "YOUR_REGISTRATION_TOKEN_1",
    // ...
    "YOUR_REGISTRATION_TOKEN_n"
);

MulticastMessage message = MulticastMessage.builder()
    .putData("score", "850")
    .putData("time", "2:45")
    .addAllTokens(registrationTokens)
    .build();
BatchResponse response = FirebaseMessaging.getInstance().sendMulticast(message);
// See the BatchResponse reference documentation
// for the contents of response.
System.out.println(response.getSuccessCount() + " messages were sent successfully");

```

**Comment by alishah730** [comment]
its because of firebase SDk
'''
<dependency>
			<groupId>com.google.firebase</groupId>
			<artifactId>firebase-server-sdk</artifactId>
			<version>3.0.3</version>
		</dependency>
'''

and 

'''
            <dependency>
		    <groupId>com.google.firebase</groupId>
		    <artifactId>firebase-admin</artifactId>
		    <version>6.11.0</version>
		</dependency>
'''

removed server sdk and its working.
