### ISSUE TITLE
`StorageException` regardless of proper service account setup

### ISSUE THREAD

**Issue by Kshitij09** [firebase/firebase-admin-java#455]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: 5.6.16-1-MANJARO (Linux)
  * Firebase SDK version: 6.9.0
  * Library version: same
  * Firebase Product: storage

### [REQUIRED] Step 3: Describe the problem

I'm using [ktor](https://ktor.io/)  to handle firebase-admin-sdk and have been trying to access firebase-storage through it. I tried to create a service account both from firebase console and google cloud console with necessary roles.
![image](https://user-images.githubusercontent.com/23584666/87863064-b6e3e780-c974-11ea-9576-474df5980858.png). Referring to the [firebase-docs](https://firebase.google.com/docs/storage/admin/start?authuser=0#java), I'm trying to establish a connection to a storage bucket from firebase but I'm getting the following Exception
```
StorageException: Error getting access token for service account: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
```

#### Steps to reproduce:
1. Clone this [repository](https://github.com/Kshitij09/ktor-torchserve-middleware)
1. You'll find the following code snippet being used to integrate firebase-admin-sdk
1. Provide a `serviceAccountKey` of your firebase project
1. Update the bucket-name accordingly
1. Run the server. You'll get the above mentioned exception

#### Relevant Code:
```kotlin
val accountSecret = environment.classLoader.getResource("serviceAccountKey.json") ?: throw FileNotFoundException()
val serviceAccount = FileInputStream(accountSecret)
val options = FirebaseOptions.Builder()
    .setCredentials(GoogleCredentials.fromStream(serviceAccount))
    .setStorageBucket("torch-experiments.appspot.com")
    .build()
val app = FirebaseApp.initializeApp(options)
StorageClient.getInstance(app).bucket()
```

#### Debugging
- [x] account-key file is being read properly
- [x] FirebaseApp is also being initialized  properly with given options
- [x] Tried specifying bucket-name in `StorageClient` call as well, didn't work
- [x] Tried `StorageClient.getInstance()` (no app reference), didn't work

I suspect the issue is only with the last line from the snippet, IE
```kotlin
StorageClient.getInstance(app).bucket()
```

#### Stacktrace

Full stacktrace of this error
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:166)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:384)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:330)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:275)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:274)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:290)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:272)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:125)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:126)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:26)
	at com.kshitijpatil.ApplicationKt.main(Application.kt:19)
Caused by: com.google.cloud.storage.StorageException: Error getting access token for service account: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:225)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:402)
	at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:213)
	at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:210)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:209)
	at com.google.firebase.cloud.StorageClient.bucket(StorageClient.java:97)
	at com.google.firebase.cloud.StorageClient.bucket(StorageClient.java:80)
	at com.kshitijpatil.ApplicationKt.firebaseInit(Application.kt:51)
	at com.kshitijpatil.ApplicationKt.module(Application.kt:26)
	at com.kshitijpatil.ApplicationKt.module$default(Application.kt:23)
	... 24 more
Caused by: java.io.IOException: Error getting access token for service account: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:360)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:165)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:151)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:430)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:399)
	... 35 more
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1094)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:358)
	... 46 more

Process finished with exit code 1
```

**Comment by Kshitij09** [comment]
Fixed it. It was my system's timezone issue. Following posts from manjaro forum helped me in fixing this issue:

https://forum.manjaro.org/t/howto-get-your-time-timezone-right-using-manjaro-windows-dual-boot/89359
https://forum.manjaro.org/t/correct-time-not-being-shown-manjaro-linux/109621

**Comment by Kshitij09** [comment]
Fixed it. It was my system's timezone issue. Following posts from manjaro forum helped me in fixing this issue:

https://forum.manjaro.org/t/howto-get-your-time-timezone-right-using-manjaro-windows-dual-boot/89359
https://forum.manjaro.org/t/correct-time-not-being-shown-manjaro-linux/109621

**Comment by ayitinya** [comment]
@Kshitij09 seems the urls don't lead anywhere anymore

How did you fix it

> Fixed it. It was my system's timezone issue. Following posts from manjaro forum helped me in fixing this issue:
> 
> https://forum.manjaro.org/t/howto-get-your-time-timezone-right-using-manjaro-windows-dual-boot/89359 https://forum.manjaro.org/t/correct-time-not-being-shown-manjaro-linux/109621
