### ISSUE TITLE
FirebaseMessagingException: Unexpected HTTP response with status: 401 null

### ISSUE THREAD

**Issue by nickelsen** [firebase/firebase-admin-java#486]
* Operating System version: Amazon Linux (on AWS Lambda), macOS 10.14.6 (openjdk 1.8.0_265)
  * Firebase SDK version: 7.0.1
  * Library version: 7.0.1
  * Firebase Product: messaging

Our implementation that uses `FirebaseMessaging.send` works most of the time and sends push notifications to apps. For some device tokens, we get the following exception:

```
FirebaseMessagingException: Unexpected HTTP response with status: 401
null
	at com.google.firebase.messaging.FirebaseMessagingException.withMessagingErrorCode(FirebaseMessagingException.java:47)
...
```

<details><summary>Full stacktrace</summary>

```
com.google.firebase.messaging.FirebaseMessagingException: Unexpected HTTP response with status: 401
null
	at com.google.firebase.messaging.FirebaseMessagingException.withMessagingErrorCode(FirebaseMessagingException.java:47)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:293)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:282)
	at com.google.firebase.internal.AbstractHttpErrorHandler.handleHttpResponseException(AbstractHttpErrorHandler.java:57)
	at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:108)
	at com.google.firebase.internal.ErrorHandlingHttpClient.sendAndParse(ErrorHandlingHttpClient.java:72)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendSingleRequest(FirebaseMessagingClientImpl.java:127)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl.send(FirebaseMessagingClientImpl.java:113)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:135)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:132)
	at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:102)
	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:86)
	at com.leoilab.scabies.notifier.FirebaseClientLive.send(FirebaseClient.scala:40)
	at com.leoilab.scabies.notifier.PushNotificationClientImpl.$anonfun$sendNotification$1(PushNotificationClient.scala:70)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:489)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.client.http.HttpResponseException: 401 Unauthorized
POST https://fcm.googleapis.com/v1/projects/<projectId>/messages:send
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1113)
	at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:96)
	... 16 common frames omitted

```
</details>

We would expect this kind of failure to be recognized and handled by the Admin SDK.

We cannot provide a repro without supplying our credentials. The `projectId` in the stacktrace is removed.

What can we do to obtain more information about what went wrong? It appears that the body of the HttpResponseException is `null`, so there's little information to go by.

**Comment by hiranya911** [comment]
It's pretty unusual for the FCM service to respond with a 401 error with no additional details. It's even more strange that it only happens for certain tokens. Do you know what these tokens are? Do they always result in this error?

> What can we do to obtain more information about what went wrong?

I'd recommend logging the platform and service errors. See https://firebase.google.com/docs/reference/admin/error-handling for details. Also share at least a code snippet to show how you're using these APIs.

**Comment by nickelsen** [comment]
Yes, we are also very puzzled, but maybe this is a better case for Firebase Support, since there's not much to go by for the SDK. Also, it has happened for 3 out of hundreds of users, however, the 3 cases appear unrelated, hence the investigation.

> Do you know what these tokens are?

They have been registered by mobile devices, using tokens from both Android and iOS `FirebaseInstanceId` API.

> Do they always result in this error?

Yes

> logging the platform and service errors

Platform error code: UNAUTHENTICATED
Service error code: null
HttpResponseCode code: 401

> share at least a code snippet to show how you're using these APIs.

The Scala code below will send a push notification when using a 'good' token and fail with the above error when using one of the 'bad' tokens.

```
import java.io.{File, FileInputStream}

import com.google.auth.oauth2.GoogleCredentials
import com.google.firebase.messaging.{FirebaseMessaging, Message, Notification}
import com.google.firebase.{FirebaseApp, FirebaseOptions}

object FirebaseTest extends App {
  val goodDeviceToken: String = ""
  val badDeviceToken: String = ""

  val configFile = new FileInputStream(new File("serviceAccountKey.json"))
  val options = FirebaseOptions
    .builder()
    .setCredentials(GoogleCredentials.fromStream(configFile))
    .setDatabaseUrl("https://***.firebaseio.com")
    .build()

  FirebaseApp.initializeApp(options)

  val message = Message
    .builder()
    .setToken(badDeviceToken)
    .setNotification(Notification.builder().setBody("testing notifications").build())
    .build()

  FirebaseMessaging.getInstance().send(message)

}
```

**Comment by chong-shao** [comment]
For token from iOS devices, FCM service forwards the message to Apple's APNS. 401 may indicate an invalid APNS credential error. 

Yes for this case it's better to reach out to Firebase support and share more information with them including the tokens for further investigation.

**Comment by gabrielmusskopf** [comment]
@nickelsen Do you have a solution or workaround for this case? I'm facing the same issue on version 9.2.0

**Comment by viccomx** [comment]
@nickelsen were you able to find out root case of this?

**Comment by nickelsen** [comment]
@viccomx No, unfortunately not.

**Comment by dxavier86** [comment]
Any one has a solution in this problem, I have the same error using in Spring Boot
