### ISSUE TITLE
unexpected/unparsable response

### ISSUE THREAD

**Issue by qeepcologne** [firebase/firebase-admin-java#506]
When calling FirebaseMessaging.getInstance().send(message), sometimes it failes with strange exception.
Sometimes no errors for a day, sometime hundreds or thousands errors. Average error rate was about 3% mid december
but is much higher today.

i checked Firebase Cloud Messaging Api in Google Cloud Platform console and see increasing
404 answer for Api Method google.firebase.fcm.v1.FcmService.SendMessage

I tried to understand the code and i think the http answer is not as expected.
Probably this is related to the firebase server infrastructure, but sdk should not fail on parsing the error and answer
some server Exception instead?.

`java.lang.IllegalArgumentException: key details
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:900) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:360) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:318) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:162) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:144) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.safeParse(FirebaseMessagingClientImpl.java:308) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:292) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:282) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.AbstractHttpErrorHandler.handleHttpResponseException(AbstractHttpErrorHandler.java:57) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:108) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.ErrorHandlingHttpClient.sendAndParse(ErrorHandlingHttpClient.java:72) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendSingleRequest(FirebaseMessagingClientImpl.java:127) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl.send(FirebaseMessagingClientImpl.java:113) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:135) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:132) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:102) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:86) ~[firebase-admin-7.1.0.jar:?]
        at de.k2interactive.qeep.api.firebase.FirebaseAdminApi.sendMessage(FirebaseAdminApi.java:70) ~[classes/:?]
        at de.k2interactive.qeep.api.firebase.FirebaseSinkV1Impl.sendSingleMessageInt(FirebaseSinkV1Impl.java:130) ~[classes/:?]
        at de.k2interactive.qeep.api.notification.NotificationSink.pushFcmReactivation(NotificationSink.java:356) ~[classes/:?]
        at de.k2interactive.qeep.jobs.FcmReactivationJob.lambda$sendAll$0(FcmReactivationJob.java:89) ~[qeep-jobs-55.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: key details, field private java.util.Map com.google.firebase.messaging.internal.MessagingServiceErrorResponse.error
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:900) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:451) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:787) ~[google-http-client-1.38.0.jar:1.38.0]
        ... 22 more
Caused by: java.lang.IllegalArgumentException: key details, field private java.util.Map com.google.firebase.messaging.internal.MessagingServiceErrorResponse.error
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:900) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseMap(JsonParser.java:679) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:783) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:451) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:787) ~[google-http-client-1.38.0.jar:1.38.0]
        ... 22 more
Caused by: java.lang.IllegalArgumentException: expected collection or array type but got class java.lang.Object
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[guava-29.0-android.jar:?]
        at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:67) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:724) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseMap(JsonParser.java:679) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:783) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:451) ~[google-http-client-1.38.0.jar:1.38.0]
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:787) ~[google-http-client-1.38.0.jar:1.38.0]
        ... 22 more`

**Comment by hiranya911** [comment]
@chong-shao looks like FCM is returning 404 HTML responses. Can you take a look?

**Comment by qeepcologne** [comment]
think so, that the response format is wrong: maybe html or xml instead of json?
I tried to reproduce the response.
I logged the Message object from firebase via:
`        ByteArrayOutputStream out = new ByteArrayOutputStream();
        new JsonHttpContent(JacksonFactory.getDefaultInstance(), fcm.wrapForTransport(false)).writeTo(out);
        return out.toString();`
create access token via:
`            GoogleCredentials gc = ServiceAccountCredentials.fromStream(new FileInputStream(accountFile)).createScoped("https://www.googleapis.com/auth/firebase.messaging");
            gc.refreshIfExpired();
            String token = gc.refreshAccessToken().getTokenValue();`
and post it from postman to:
https://fcm.googleapis.com/v1/projects/{projectId}/messages:send manually and the only error i got is:
`{
    "error": {
        "code": 404,
        "message": "Requested entity was not found.",
        "status": "NOT_FOUND",
        "details": [
            {
                "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
                "errorCode": "UNREGISTERED"
            }
        ]
    }
}`
which looks totally valid for me.

**Comment by hiranya911** [comment]
That's the error you'd expect to see. But it seems intermittently FCM responds with a 404 HTML response.

**Comment by qeepcologne** [comment]
I check last 10 errors with postman. All of them produce the error i posted above. I don't know why the sdk can't handle this error anymore

**Comment by hiranya911** [comment]
If you can repro this in your server can you enable debug logs on it, and share the logs when the error occurs again?

**Comment by hiranya911** [comment]
That seems to be an issue with the routing/hosting layer of the FCM service. The request is not even reaching the FCM backend service. It's failing much earlier, which is why there's no wellformed FCM error response or error code.

@chong-shao you might want to take look at this.

**Comment by qeepcologne** [comment]
error went away for some time, but this morning and after udated google-http-client to 1.39 i got:
``
java.lang.IllegalArgumentException:
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:900) ~[google-http-client-1.39.0.jar:1.39.0]
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:360) ~[google-http-client-1.39.0.jar:1.39.0]
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:318) ~[google-http-client-1.39.0.jar:1.39.0]
        at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:162) ~[google-http-client-1.39.0.jar:1.39.0]
        at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:144) ~[google-http-client-1.39.0.jar:1.39.0]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.safeParse(FirebaseMessagingClientImpl.java:308) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:292) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:282) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.AbstractHttpErrorHandler.handleHttpResponseException(AbstractHttpErrorHandler.java:57) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:108) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.ErrorHandlingHttpClient.sendAndParse(ErrorHandlingHttpClient.java:72) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendSingleRequest(FirebaseMessagingClientImpl.java:127) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessagingClientImpl.send(FirebaseMessagingClientImpl.java:113) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:135) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:132) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:102) ~[firebase-admin-7.1.0.jar:?]
        at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:86) ~[firebase-admin-7.1.0.jar:?]
        at de.k2interactive.qeep.api.firebase.FirebaseAdminApi.sendMessage(FirebaseAdminApi.java:74) ~[classes/:?]
        at de.k2interactive.qeep.api.firebase.FirebaseSinkV1Impl.sendSingleMessageInt(FirebaseSinkV1Impl.java:130) ~[classes/:?]
        at de.k2interactive.qeep.api.firebase.FirebaseSinkV1Impl.lambda$sendSingleMessage$0(FirebaseSinkV1Impl.java:74) ~[classes/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: expected primitive class, but got: class com.google.firebase.messaging.internal.MessagingServiceErrorResponse
        at com.google.api.client.util.Data.parsePrimitiveValue(Data.java:478) ~[google-http-client-1.39.0.jar:1.39.0]
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:869) ~[google-http-client-1.39.0.jar:1.39.0]
        ... 21 more
``

i also enabled logging today to get the full response code + response, but currently no error occurs.

**Comment by hiranya911** [comment]
This error is slightly different from the one in the original report. But I think it's related to the same problem. Thanks for enabling logging @qeepcologne. Hopefully we can isolate the offending response soon. I will also find some time to repro the error on my end with some unit tests.

**Comment by chong-shao** [comment]
I suspect the error @qeepcologne  saw has a different cause from the one @mohamedhafez reported . Yesterday there was an identified issue on 404 HTML errors in the backend that affect ~2% traffic, which I believe is the one @mohamedhafez reported. That issue has been fixed around 12am today.

**Comment by hiranya911** [comment]
> I suspect the error @qeepcologne saw has a different cause from the one @mohamedhafez reported

Yes, I believe that's right. In one case there's a `FirebaseMessagingException` (i.e. graceful failure), and in the other there's an unexpected `IllegalArgumentException`.

**Comment by hiranya911** [comment]
@qeepcologne please try out the last release of the SDK (v7.1.1) and see if that helps you avoid the runtime exception, and better debug the problem.

**Comment by qeepcologne** [comment]
currently no errors occur, but anyway i updated to 7.1.1 today.

**Comment by yuchenit** [comment]
I also encountered this error, my firebase-admin version is v8.1.0, how can I solve this problem?
Here are the error details:
com.google.firebase.messaging.FirebaseMessagingException: Requested entity was not found.
	at com.google.firebase.messaging.FirebaseMessagingException.withMessagingErrorCode(FirebaseMessagingException.java:51)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:293)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:282)
	at com.google.firebase.internal.AbstractHttpErrorHandler.handleHttpResponseException(AbstractHttpErrorHandler.java:57)
	at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:108)
	at com.google.firebase.internal.ErrorHandlingHttpClient.sendAndParse(ErrorHandlingHttpClient.java:72)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendSingleRequest(FirebaseMessagingClientImpl.java:127)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl.send(FirebaseMessagingClientImpl.java:113)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:137)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:134)
	at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:104)
	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:86)
	at com.camojojo.user.common.utils.FireBaseUtil.sendMsg(FireBaseUtil.java:85)
	at com.camojojo.user.common.utils.FireBaseUtil.main(FireBaseUtil.java:101)
Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
POST https://fcm.googleapis.com/v1/projects/camojojo-339c0/messages:send
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "UNREGISTERED"
      }
    ]
  }
}

**Comment by yuchenit** [comment]
I also encountered this error, my firebase-admin version is v8.1.0, how can I solve this problem?
[error_log.txt](https://github.com/firebase/firebase-admin-java/files/9642707/error_log.txt)

**Comment by yuchenit** [comment]
I also encountered this error, my firebase-admin version is v8.1.0, how can I solve this problem?
Here are the error details:
com.google.firebase.messaging.FirebaseMessagingException: Requested entity was not found.
	at com.google.firebase.messaging.FirebaseMessagingException.withMessagingErrorCode(FirebaseMessagingException.java:51)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:293)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:282)
	at com.google.firebase.internal.AbstractHttpErrorHandler.handleHttpResponseException(AbstractHttpErrorHandler.java:57)
	at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:108)
	at com.google.firebase.internal.ErrorHandlingHttpClient.sendAndParse(ErrorHandlingHttpClient.java:72)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendSingleRequest(FirebaseMessagingClientImpl.java:127)
	at com.google.firebase.messaging.FirebaseMessagingClientImpl.send(FirebaseMessagingClientImpl.java:113)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:137)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:134)
	at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:104)
	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:86)
	at com.camojojo.user.common.utils.FireBaseUtil.sendMsg(FireBaseUtil.java:85)
	at com.camojojo.user.common.utils.FireBaseUtil.main(FireBaseUtil.java:101)
Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
POST https://fcm.googleapis.com/v1/projects/camojojo-339c0/messages:send
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "UNREGISTERED"
      }
    ]
  }
}

**Comment by yuchenit** [comment]
“FirebaseMessagingException: Requested entity was not found ” 
Is this error related to the user device token and can I ignore the error because I found some users don't get the error.
