### ISSUE TITLE
[Firebase Messaging] SSL error when trying to send an FCM message

### ISSUE THREAD

**Issue by cadaniel** [firebase/firebase-admin-java#565]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Docker: openjdk:11-jre-slim
  * Firebase SDK version: NA - Backend only problem
  * Library version: 7.3.0
  * Firebase Product: Messaging

### [REQUIRED] Step 3: Describe the problem

SSL error

<details>
  <summary>javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source) </summary>
 
``` 
  com.google.firebase.messaging.FirebaseMessagingException: Unknown error while making a remote service call: Remote host terminated the handshake at com.google.firebase.messaging.FirebaseMessagingException.withMessagingErrorCode(FirebaseMessagingException.java:47) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:293) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:282) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.internal.AbstractHttpErrorHandler.handleIOException(AbstractHttpErrorHandler.java:63) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:110) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.internal.ErrorHandlingHttpClient.sendAndParse(ErrorHandlingHttpClient.java:72) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendSingleRequest(FirebaseMessagingClientImpl.java:127) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessagingClientImpl.send(FirebaseMessagingClientImpl.java:113) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:137) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:134) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:104) 
    [firebase-admin-7.3.0.jar!/:na] at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:86) 
    [firebase-admin-7.3.0.jar!/:na] at ca.mynormative.api.tasks.PushNotificationsTasks.sendNotificationToFcm(PushNotificationsTasks.kt:239) 
    [classes!/:na] at ca.mynormative.api.tasks.PushNotificationsTasks.sendNotifications(PushNotificationsTasks.kt:64) 
    [classes!/:na] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
    [na:na] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
    [na:na] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
    [na:na] at java.base/java.lang.reflect.Method.invoke(Unknown Source) 
    [na:na] at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) 
    [spring-context-5.3.1.jar!/:5.3.1] at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) 
    [spring-context-5.3.1.jar!/:5.3.1] at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) 
    [spring-context-5.3.1.jar!/:5.3.1] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
    [na:na] at java.base/java.util.concurrent.FutureTask.run(Unknown Source) 
    [na:na] at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) 
    [na:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
    [na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
    [na:na] at java.base/java.lang.Thread.run(Unknown Source) 
    [na:na] Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) 
    [na:na] at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) 
    [na:na] at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) 
    [na:na] at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) 
    [na:na] at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) 
    [na:na] at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) 
    [na:na] at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113) 
    [google-http-client-1.39.2.jar!/:1.39.2] at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) 
    [google-http-client-1.39.2.jar!/:1.39.2] at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) 
    [google-http-client-1.39.2.jar!/:1.39.2] at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:96) 
    [firebase-admin-7.3.0.jar!/:na] ... 23 common frames omitted Suppressed: java.net.SocketException: Broken pipe (Write failed) at java.base/java.net.SocketOutputStream.socketWrite0(Native Method) 
    [na:na] at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source) 
    [na:na] at java.base/java.net.SocketOutputStream.write(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) 
    [na:na] ... 34 common frames omitted Caused by: java.io.EOFException: SSL peer shut down incorrectly at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source) 
    [na:na] at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source) 
    [na:na] ... 36 common frames omitted

```
</details>

#### Steps to reproduce:

My backend tried to send a message to FCM, pretty basic message below. 

#### Relevant Code:

Send to firebase
```

	private fun sendNotificationToFcm(token: String, title: String?, body: String?, topicId: String, questionId: Int?) {
		val notification = Notification.builder()
		notification.setBody(body)
		notification.setTitle(title)

		val notificationMessage = Message.builder()
		notificationMessage.setToken(token)
		notificationMessage.setNotification(notification.build())
		notificationMessage.putData("priority", "high")
		notificationMessage.putData("collapseKey", topicId)
		notificationMessage.putData("apns-collapse-id", topicId)
		if (questionId != null) {
			notificationMessage.putData("questionId", "$questionId")
		}

		firebaseMessaging.send(notificationMessage.build())
	}
```

firebaseMessaging bean

```
@Configuration
class FirebaseConfiguration(
	@Value("\${firebase.firebase-config}") val configFile: String,
	@Value("\${firebase.firebase-url}") val dbUrl: String) {

	private val logger: Logger = LoggerFactory.getLogger(FirebaseConfiguration::class.java)

	@Bean
	fun initFirebaseMessaging(): FirebaseMessaging {
		val firebaseApp = initFirebaseApp()
		return FirebaseMessaging.getInstance(firebaseApp)
	}

	@Bean
	fun initFirebaseApp(): FirebaseApp {
		val classloader = Thread.currentThread().contextClassLoader
		val firebaseInputStream = classloader.getResourceAsStream(configFile)

		val options = FirebaseOptions.builder()
		options.setCredentials(GoogleCredentials.fromStream(firebaseInputStream))
		options.setDatabaseUrl(dbUrl)
		return FirebaseApp.initializeApp(options.build())
	}

	@Bean
	fun firebaseAuth(): FirebaseAuth {
		val app = initFirebaseApp()
		return FirebaseAuth.getInstance(app)
	}
}
```

Worth noting that the docker container is hosted using google cloud run

**Comment by cadaniel** [comment]
Seems to have solved itself.

**Comment by sryze** [comment]
Same issue here, but with the REST API (without Admin SDK).
