### ISSUE TITLE
com.google.api.gax.rpc.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: google.firestore.v1.Firestore/RunAggregationQuery

### ISSUE THREAD

**Issue by HideakiSago** [firebase/firebase-admin-java#731]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Monterey (12.6)
  * Firebase SDK version: 9.1.0
  * Library version: 9.1.0
  * Firebase Product: Cloud Firestore

```build.gradle.kts
    // Google Cloud Platform
    implementation(platform("com.google.cloud:libraries-bom:26.1.3"))
    implementation("com.google.cloud:google-cloud-core")
    implementation("com.google.cloud:google-cloud-logging")

    // Firebase
    implementation("com.google.firebase:firebase-admin:9.1.0")

    // BigQuery
    implementation("com.google.cloud:google-cloud-bigquery:2.17.1")
```

### [REQUIRED] Step 3: Describe the problem

UnimplementedException is thrown from ApiFuture<AggregateQuerySnapshot>.get().

#### Steps to reproduce:

```log
Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: google.firestore.v1.Firestore/RunAggregationQuery
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:55)
	at ...
Caused by: com.google.api.gax.rpc.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: google.firestore.v1.Firestore/RunAggregationQuery
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:108)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
	at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:84)
	at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: google.firestore.v1.Firestore/RunAggregationQuery
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 14 more
```

#### Relevant Code:

```kotlin
    override fun existsAll(ids: Collection<String>): Boolean = collection
        .whereIn(FieldPath.documentId(), ids.toList())
        .count()
        .get()
        .get() // UnimplementedException thrown.
        .let { it.count == ids.size.toLong() }
```

**Comment by dconeybe** [comment]
@HideakiSago Since this issue is 2 months old, could you try to reproduce with the latest version of all of the dependencies? Notably, `com.google.cloud:libraries-bom:26.1.3` probably needs to be 26.1.4 or 26.1.5 to include the `RunAggregationQuery` RPC.

**Comment by lahirumaramba** [comment]
Closing due to inactivity, we can reopen later if needed.
