### ISSUE TITLE
java.lang.IllegalArgumentException: key details

### ISSUE THREAD

**Issue by kurenchuksergey** [firebase/firebase-admin-java#733]
Hi, I met the same problem as described [there](https://github.com/firebase/firebase-admin-java/issues/506) (but it closed) on firebase-admin-java SDK 8.1.0
I got it in the production environment, under pressure. Unfortunately, I can't enable the CONFIG log level on production to get logs for these errors, but I have the stack trace (which seems similar)
`java.lang.IllegalArgumentException: key details
    at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:900)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:360)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
    at com.google.api.client.googleapis.batch.BatchUnparsedResponse.getParsedDataClass(BatchUnparsedResponse.java:223)
    at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:208)
    at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:149)
    at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:268)
    at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendBatchRequest(FirebaseMessagingClientImpl.java:138)
    at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendAll(FirebaseMessagingClientImpl.java:118)
    at com.google.firebase.messaging.FirebaseMessaging$2.execute(FirebaseMessaging.java:295)
    at com.google.firebase.messaging.FirebaseMessaging$2.execute(FirebaseMessaging.java:292)
    at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
    at com.google.firebase.messaging.FirebaseMessaging.sendAll(FirebaseMessaging.java:183)
    at com.google.firebase.messaging.FirebaseMessaging.sendAll(FirebaseMessaging.java:158)
    `
Can we solve the problem or add some code to catch raw answer from  FCM?

**Comment by lahirumaramba** [comment]
Hey @chong-shao, do you think this is related to b/256882066?

**Comment by chong-shao** [comment]
Hi @lahirumaramba I think it's not related to the bug: the bug you linked is about Authentication error.

For the IllegalArgumentException it would be easier to debug if the raw answer from FCM can be printed. @lahirumaramba , is it possible to do that in Admin SDK FCM batch sends?

**Comment by kurenchuksergey** [comment]
is it any way to trace only requests with the errors? How I have noticed we are meeting this problem only under pressure. It seems we get some unexpected answers from FCM

**Comment by lahirumaramba** [comment]
Hey @kurenchuksergey,

Thanks for your patience on this. It seems like you are looking for a way to enable debug logs so you can investigate the response from the FCM server.

The Admin Java SDK uses SLF4j as a logging facade, but most GCP libraries that the Admin SDK depends on logs directly to the JUL framework. You can configure how JUL operates by creating a `logging.properties` file for your app, and setting the `-Djava.util.logging.config.file` system property to point to that file when executing the application.

The way you can configure this depends on your production environment.

For more details on how logs work please see: https://hiranya911.medium.com/logging-in-java-libraries-for-firebase-and-google-cloud-platform-f8742493b73f

**Comment by lahirumaramba** [comment]
Closing due to inactivity, we can reopen later if needed.
