### ISSUE TITLE
Serializing java.time.LocalDate throws exception

### ISSUE THREAD

**Issue by ghajba** [firebase/firebase-admin-java#86]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Sierra 10.12
  * Firebase SDK version: 5.3.1
  * Library version: ?
  * Firebase Product: database

### [REQUIRED] Step 3: Describe the problem

When I try to serialize a `LocalDate` I get the following exception.

```
com.google.firebase.database.DatabaseException: Found conflicting getters for name: getChronology
	at com.google.firebase.database.utilities.encoding.CustomClassMapper$BeanMapper.<init>(CustomClassMapper.java:476) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.loadOrCreateBeanMapperForClass(CustomClassMapper.java:324) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.serialize(CustomClassMapper.java:168) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.access$2(CustomClassMapper.java:117) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:806) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.serialize(CustomClassMapper.java:169) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.access$2(CustomClassMapper.java:117) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:806) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.serialize(CustomClassMapper.java:169) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.serialize(CustomClassMapper.java:143) ~[classes/:na]
	at com.google.firebase.database.utilities.encoding.CustomClassMapper.convertToPlainJavaTypes(CustomClassMapper.java:68) ~[classes/:na]
	at com.google.firebase.database.DatabaseReference.setValueInternal(DatabaseReference.java:321) ~[classes/:na]
	at com.google.firebase.database.DatabaseReference.setValue(DatabaseReference.java:229) ~[classes/:na]
	at com.google.firebase.database.DatabaseReference.setValueAsync(DatabaseReference.java:180) ~[classes/:na]
```

The cause is, that `LocalDate` overrides the `java.time.chrono.ChronoLocalDate.getChronology()` method which returns a `java.time.chrono.Chronology`. The override returns `java.time.chrono.IsoChronology` which is an implementation of the original return type.

Question: how can such overrides be addressed in the future that such classes (available in core Java or other libraries without access) can be serialized? If we can figure this out, I am happy to create a PR with the implementation.

**Comment by hiranya911** [comment]
@schmidt-sebastian is this something we ought to support?

**Comment by dimitraz** [comment]
Is there a follow up to this? I'm having the same problem

**Comment by hiranya911** [comment]
We currently have no plans to support serialization of these date types. Please use `java.util.Date` in the meantime.

Related to #75

**Comment by PlusLake** [comment]
Here is 2024 now and JSR 310 (java.time) was shipped in Java 8 from 10 years ago.
Users would be very happy if we don't need to deal with the conversion problem anymore.

Currently I copy paste this snippet to my project every time,
just to transforming the data classes for using Firestore.

```kotlin
fun Any.toFirestoreObject() = this.javaClass.declaredFields.associate {
    it.isAccessible = true
    val transform = converters[it.type.kotlin] ?: { it }
    it.name to transform(it.get(this))
}

val converters = hashMapOf<KClass<*>, (Any) -> Any>(
    LocalDate::class to { Timestamp.valueOf((it as LocalDate).atStartOfDay()) },
    LocalDateTime::class to { Timestamp.valueOf(it as LocalDateTime) }
)
```

**Comment by smil2k** [comment]
I never thought that Google will behave like IBM. No sane person should use java.util.Date in 2024.
Happy new year, sad to see a great company goes down to line.
